// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team_7WebAPI.DataAccessLayer;

namespace Team_7WebAPI.Migrations
{
    [DbContext(typeof(DataAccessLayer_Db))]
    partial class DataAccessLayer_DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Team_7WebAPI.Model.Manager_Details_Section_Db", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobile_Number")
                        .HasColumnType("int");

                    b.HasKey("Employee_ID");

                    b.ToTable("manager_Details_Section_Dbs");
                });

            modelBuilder.Entity("Team_7WebAPI.Model.My_Details_Section_Db", b =>
                {
                    b.Property<int>("Employee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Available_Leave_Balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_Joined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Mobile_Number")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employee_Id");

                    b.ToTable("my_Details_Section_Dbs");
                });

            modelBuilder.Entity("Team_7WebAPI.Model.My_Leave_Application_Section_Db", b =>
                {
                    b.Property<int>("Leave_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Applied_ON")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leave_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number_of_Days")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Leave_ID");

                    b.ToTable("My_Leave_Application_Section_Dbs");
                });
#pragma warning restore 612, 618
        }
    }
}
