name: Workflow 1

on:
  push:
    branches:
      - master

jobs:
  job1:
#     strategy:
#       matrix:
#         runner: [ubuntu-latest, windows-latest] # Add the names of your self-hosted runners here
#     runs-on: ${{ matrix.runner }}
    runs-on: [ubuntu-latest,windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run workflow 1
        run: echo "Running workflow 1 on runner $RUNNER_NAME"
  job2:
      runs-on: [ubuntu-latest,windows-latest]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run workflow 2
          run: echo "Running workflow 2 on runner $RUNNER_NAME"
